name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Prepare Production Files
        run: |
          mkdir production
          cp -r dist/* production/
          cp -r backend production/backend

      - name: Deploy to Hostinger
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: ${{ secrets.PORT }}
          source: "production/*"
          target: "/home/u433748162/domains/matrimony.rukmantech.com/public_html"
          strip_components: 1
          overwrite: true
